version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: segments_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fgGxgIllJf
    ports:
      - 5432:5432
  app:
    links: 
      - postgres
    depends_on:
      - postgres
    container_name: app
    build: .
    ports:
      - 8080:8080
    volumes: 
      - .:/var/server
    restart: always
