version: '3.1'

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=fgGxgIllJf'
    ports:
      - '5432'
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql