definitions:
  models.Error:
    properties:
      message:
        type: string
    type: object
  models.Segment:
    properties:
      delete_at:
        example: "2012-10-02T10:00:00-05:00"
        type: string
      name:
        example: AVITO_TEST_VOICES
        type: string
      per_cent:
        example: 33
        type: integer
    required:
    - name
    type: object
  models.User:
    properties:
      id:
        example: 13214
        type: integer
      segments:
        items:
          $ref: '#/definitions/models.Segment'
        type: array
    type: object
info:
  contact: {}
paths:
  /api/v1/segments:
    post:
      consumes:
      - application/json
      description: create segment
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Segment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Create segment
      tags:
      - segments
  /api/v1/segments/{name}:
    delete:
      description: deletes segment (also deletes it from users)
      operationId: create-segment
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Delete segment
      tags:
      - segments
  /api/v1/users/{id}/segments:
    get:
      consumes:
      - application/json
      description: Deletes user's segments
      operationId: update-user-segments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Update user's segments
      tags:
      - users
swagger: "2.0"
